// <auto-generated />
using CliniKey.Infrastructure.Identity;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CliniKey.Infrastructure.Persistence.Migrations.Auth
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260523000000_RemoveRolesSeedData")]
    partial class RemoveRolesSeedData
    {
    }
}
